#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import os
import json
import secrets
import sys

# agent is a NethServer library which provides function to communicate with the agent
import agent

data = json.load(sys.stdin)

# Setup default values
auth_token = ""
if os.path.exists("n8n.env"):
    dt = agent.read_envfile("n8n.env")
    auth_token = dt.get("N8N_RUNNERS_AUTH_TOKEN")
    if auth_token == "":
        auth_token = secrets.token_urlsafe(32)
else:
    auth_token = secrets.token_urlsafe(32)


if not os.path.exists("n8n-db.env"):
    if os.path.exists("database.env"):
        db = agent.read_envfile("database.env")
        random_key = secrets.token_hex(16)
        n8n_config = {
            "DB_TYPE": "postgresdb",
            "DB_POSTGRESDB_HOST": "n8n-pgsql",
            "DB_POSTGRESDB_PORT": "5432",
            "DB_POSTGRESDB_DATABASE": db.get("POSTGRES_DATABASE"),
            "DB_POSTGRESDB_USER": db.get("POSTGRES_NON_ROOT_USER"),
            "DB_POSTGRESDB_PASSWORD": db.get("POSTGRES_NON_ROOT_PASSWORD"),
        }
        agent.write_envfile("n8n-db.env", n8n_config)
# n8n CSRF settings
host = data.get("host", "")
timezone = data.get("timezone", "UTC")
n8n_URL = "https://" + host
OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS = data.get(
    "OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS", "true"
)
N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS = data.get(
    "N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS", "true"
)
N8N_RUNNERS_ENABLED = data.get("N8N_RUNNERS_ENABLED", "true")
N8N_RUNNERS_MODE = data.get("N8N_RUNNERS_MODE", "external")
N8N_RUNNERS_BROKER_LISTEN_ADDRESS = data.get(
    "N8N_RUNNERS_BROKER_LISTEN_ADDRESS", "0.0.0.0"
)
N8N_NATIVE_PYTHON_RUNNER = data.get("N8N_NATIVE_PYTHON_RUNNER", "true")
# EMAIL Settings Config
rdb = agent.redis_connect(use_replica=True)
smtp_settings = agent.get_smarthost_settings(rdb)

SMTP_HOST = smtp_settings["host"]
SMTP_PORT = smtp_settings["port"]
SMTP_USERNAME = smtp_settings["username"]
SMTP_PASSWORD = smtp_settings["password"]

n8n_config = {
    "GENERIC_TIMEZONE": timezone,
    "TZ": timezone,
    "N8N_HOST": n8n_URL,
    "EXECUTIONS_MODE": "queue",
    "QUEUE_BULL_REDIS_HOST": "n8n-redis",
    "QUEUE_BULL_REDIS_PORT": "6379",
    "QUEUE_HEALTH_CHECK_ACTIVE": "true",
    "N8N_EMAIL_MODE": "smtp",
    "N8N_SMTP_SSL": "false",
    "N8N_SMTP_HOST": SMTP_HOST,
    "N8N_SMTP_PORT": SMTP_PORT,
    "N8N_SMTP_USER": SMTP_USERNAME,
    "N8N_SMTP_PASS": SMTP_PASSWORD,
    "N8N_SMTP_SENDER": SMTP_USERNAME,
    "OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS": OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS,
    "N8N_RUNNERS_ENABLED": N8N_RUNNERS_ENABLED,
    "N8N_RUNNERS_MODE": N8N_RUNNERS_MODE,
    "N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS": N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS,
    "N8N_RUNNERS_BROKER_LISTEN_ADDRESS": N8N_RUNNERS_BROKER_LISTEN_ADDRESS,
    "N8N_NATIVE_PYTHON_RUNNER": N8N_NATIVE_PYTHON_RUNNER,
    "N8N_RUNNERS_TASK_BROKER_URI": "http://n8n-server:5679",
    "N8N_RUNNERS_AUTH_TOKEN": auth_token,
}
agent.write_envfile("n8n.env", n8n_config)


# Talk with agent using file descriptor.


# Make sure everything is saved inside the environment file
# just before starting systemd unit
agent.dump_env()
