#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import os
import json
import sys

# agent is a NethServer library which provides function to communicate with the agent
import agent

data = json.load(sys.stdin)

# Setup default values

# n8n CSRF settings
host = data.get("host", "")
n8n_URL = "https://" + host


# EMAIL Settings Config
rdb = agent.redis_connect(use_replica=True)
smtp_settings = agent.get_smarthost_settings(rdb)

SMTP_HOST = smtp_settings["host"]
SMTP_PORT = smtp_settings["port"]
SMTP_USERNAME = smtp_settings["username"]
SMTP_PASSWORD = smtp_settings["password"]

n8n_config = {
    "GENERIC_TIMEZONE": "Europe/Berlin",
    "TZ": "Africa/Nairobi",
    "N8N_HOST": n8n_URL,
    "EXECUTIONS_MODE": "queue",
    "QUEUE_BULL_REDIS_HOST": "n8n-redis",
    "QUEUE_BULL_REDIS_PORT": "6379",
    "QUEUE_HEALTH_CHECK_ACTIVE": "true",
    "N8N_EMAIL_MODE": "smtp",
    "N8N_SMTP_SSL": "false",
    "N8N_SMTP_HOST": SMTP_HOST,
    "N8N_SMTP_PORT": SMTP_PORT,
    "N8N_SMTP_USER": SMTP_USERNAME,
    "N8N_SMTP_PASS": SMTP_PASSWORD,
    "N8N_SMTP_SENDER": SMTP_USERNAME,
}
agent.write_envfile("n8n.env", n8n_config)


# Talk with agent using file descriptor.

# Setup configuration from user input.

# Setup PHP with safe defaults
agent.set_env("PHP_ENABLE_OPCACHE", "1")
agent.set_env("PHP_MEMORY_LIMIT", "512M")
agent.set_env("N8N_HOST", host)


# Make sure everything is saved inside the environment file
# just before starting systemd unit
agent.dump_env()
